# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Master Integration

on:
  push:
    branches: 
    - main
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run lint

  test: 
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm test
      env:
        CI: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: test

    if: github.actor == 'phish108' || startsWith(github.actor, 'dependabot')
    runs-on: ubuntu-latest

    steps:
    - name: check changes
      id: release
      uses: phish108/release-check@1.0.13
      with:
        protected-paths: | 
          README.md
          .eslintrc
          LICENSE
          action.yml

    - run: | 
        echo "proceed!"
      if: ${{ steps.release.outputs.proceed == 'true' }}
    - uses: actions/checkout@v3

    - run: |
        git config --local user.email "cpglahn@gmail.com"
        git config --local user.name "Christian Glahn"

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - run: | 
        npm ci
        npm run package
        git commit -m "updated package file for $GITSHA" -a 
      if: ${{ steps.release.outputs.proceed == 'true' }}
      env:
        GITSHA: ${{ github.sha }}

    - name: Push changes
      if: ${{ steps.release.outputs.proceed == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
  
  release:
    needs: build

    if: github.actor == 'phish108' || startsWith(github.actor, 'dependabot')
    runs-on: ubuntu-latest

    steps:
    - name: check changes
      id: release
      uses: phish108/release-check@1.0.13
      with:
        protected-paths: | 
          README.md
          .eslintrc
          LICENSE
          action.yml

    - name: check changes MAIN
      id: releaseMain
      uses: phish108/release-check@main
      with:
        protected-paths: | 
          README.md
          .eslintrc
          LICENSE
          action.yml

    - id: tagger
      if: ${{ steps.release.outputs.proceed == 'true' && steps.releaseMain.outputs.proceed == 'true' }}
      uses: phish108/autotag-action@1.1.60
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dry-run: 'TRUE'

    - uses: actions/checkout@v3

    - run: |
        git config --local user.email "cpglahn@gmail.com"
        git config --local user.name "Christian Glahn"

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - run: | 
        git pull origin
        npm ci
        npm --no-git-tag-version --allow-same-version version ${{ steps.tagger.outputs.new-tag }} 
        sed -ire "s/phish108\/release-check@[0-9]*\.[0-9]*\.[0-9]*/phish108\/release-check@${{ steps.tagger.outputs.new-tag }}/g" README.md
        git commit -m "updated release files for $GITSHA" -a 
      if: ${{ steps.release.outputs.proceed == 'true' && steps.releaseMain.outputs.proceed == 'true' }}
      env:
        GITSHA: ${{ github.sha }}

    - name: Push changes
      if: ${{ steps.release.outputs.proceed == 'true' && steps.releaseMain.outputs.proceed == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - uses: phish108/autotag-action@1.1.60
      if: ${{ steps.release.outputs.proceed == 'true' && steps.releaseMain.outputs.proceed == 'true' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
